apiVersion: v1
kind: Service
metadata: 
  name: myapp-service
spec:
  type: NodePort
  ports:
    - port: 80 # service port
      targetPort: 80  # port of the pod
      nodePort: 30004 # port of the node where we'll hit the request
  selector:
    env: production