apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: myapp-replicaset
  labels:
    app: myapp
spec:
  selector:
    matchLabels:
      env: production # This should be same as below. Otherwise replicaset won't know which pods needs replication.
  replicas: 3
  template:
    metadata:
      name: nginx-2
      labels:
        env: production # This should be same as above.
    spec:
      containers:
        - name: nginx
          image: nginx
    