apiVersion: v1
kind: Service
metadata:
  name: voting-service
  labels:
    name: voting-service
    app: demo-voting-app
spec: # it will be internal service i.e. ClusterIP, which is default.
  type: NodePort
  selector:
    name: voting-app-pod
    app: demo-voting-app
  ports:
    - port: 80 # on the service
      targetPort: 80 # on the pod
      nodePort: 30004 # on the node